### ISSUE TITLE
[FEATURE] Adding a new Utterance is very hard in the new versions

### ISSUE THREAD

**Issue by bassamtantawi-botpress** [botpress/studio#102] opened 2021-09-13 20:47 UTC
v12.26.1
Now it is hard to be able to add new utterances at the end of the intent. Before, as soon as I click the last utterance, a new utterance line is added automatically.

![image](https://user-images.githubusercontent.com/89806971/133153935-56e7baaf-fe14-4cc2-bcaa-593730c3d414.png)

**Comment by franklevasseur** [comment] 2021-09-30 18:40
Hey @bassamtantawi-botpress!

I can't reproduce your issue... Mind giving me some more details ? 

1. What OS are you using?
2. What Browser are you using ?
3. Is this a new bug since v12.26.1 ? What is the last version of Botpress your tries where the bug didn't exist ?

**Comment by bassamtantawi-botpress** [comment] 2021-09-30 19:01
What OS are you using? -> Windows
What Browser are you using ? -> Chrome
How do you run Botpress ? Is it from sources, from binary or docker image ? -> Both sources and Binary
Is this a new bug since v12.26.1 ? What is the last version of Botpress your tries where the bug didn't exist ? -> last version I tried 12.17.1 I think.

**Comment by franklevasseur** [comment] 2021-09-30 19:16
Allright @bassamtantawi-botpress,

After the video call we've had few minutes ago, we arrived to the conclusion that we can't reproduce this problem.

This does not mean that there is no bug. Simply that we don't fully know how to reproduce it.

I'll close the issue for now, but feel free to re-open if you have more details. Please poke me if you do.

Thanks for your contribution,

François

**Closed by franklevasseur** 2021-09-30 19:16 UTC
